services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finance-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finance-frontend
    ports:
      - "5173:80" # 5173 externo → 80 nginx
    depends_on:
      - api

  db:
    image: postgres:15
    container_name: finance-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: finance_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: