
services:
  api:
    build: .
    container_name: finance-api
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: finance-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: finance_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: